name:                hangouts-reader
version:             0.1.0.0
github:              "Fuco1/hangouts-reader"
license:             BSD3
author:              "Matúš Goljer"
maintainer:          "matus.goljer@gmail.com"
copyright:           "Copyright: (c) 2018 Matúš Goljer"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Fuco1/hangouts-reader#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4
- bytestring
- text
- time
- prettyprinter >= 1.2.1
- optparse-applicative >= 0.14.2

library:
  source-dirs: src

executables:
  hangouts-reader:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hangouts-reader

tests:
  hangouts-reader-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hangouts-reader
